[build]
builder = "NIXPACKS"
buildCommand = "if [ -d 'backend' ]; then cd backend; fi && pip install -r requirements.txt"

[deploy]
startCommand = "if [ -d 'backend' ]; then cd backend; fi && uvicorn server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
